import { CharactersData } from './types/index.js';

export const charactersData: CharactersData = {
    "characters": {
        "1": {
            "id": 1,
            "school": "Karasuno",
            "name": "Shoyo Hinata",
            "name_jp": "日向翔陽",
            "variant": "Hanami",
            "rarity": "SP",
            "position": "MB",
            "profile_image_url": "./assets/images/characters/1_Shoyo_Hinata_Hanami.png",
            "personal_page_url": null
        },
        "2": {
            "id": 2,
            "school": "Karasuno",
            "name": "Shoyo Hinata",
            "name_jp": "日向翔陽",
            "variant": null,
            "rarity": "SSR",
            "position": "MB",
            "profile_image_url": "./assets/images/characters/2_Shoyo_Hinata.png",
            "personal_page_url": null
        },
        "3": {
            "id": 3,
            "school": "Karasuno",
            "name": "Shoyo Hinata",
            "name_jp": "日向翔陽",
            "variant": "Practice",
            "rarity": "SR",
            "position": "MB",
            "profile_image_url": "./assets/images/characters/3_Shoyo_Hinata_Practice.png",
            "personal_page_url": null
        },
        "4": {
            "id": 4,
            "school": "Karasuno",
            "name": "Tobio Kageyama",
            "name_jp": "影山飛雄",
            "variant": null,
            "rarity": "UR",
            "position": "S",
            "profile_image_url": "./assets/images/characters/4_Tobio_Kageyama.png",
            "personal_page_url": "https://naoshisan.com/?p=3456"
        },
        "5": {
            "id": 5,
            "school": "Karasuno",
            "name": "Tobio Kageyama",
            "name_jp": "影山飛雄",
            "variant": "Practice",
            "rarity": "SSR",
            "position": "S",
            "profile_image_url": "./assets/images/characters/5_Tobio_Kageyama_Practice.png",
            "personal_page_url": "https://naoshisan.com/?p=3494"
        },
        "6": {
            "id": 6,
            "school": "Karasuno",
            "name": "Daichi Sawamura",
            "name_jp": "澤村大地",
            "variant": null,
            "rarity": "SSR",
            "position": "OP",
            "profile_image_url": "./assets/images/characters/6_Daichi_Sawamura.png",
            "personal_page_url": null
        },
        "7": {
            "id": 7,
            "school": "Karasuno",
            "name": "Daichi Sawamura",
            "name_jp": "澤村大地",
            "variant": "Practice",
            "rarity": "SR",
            "position": "OP",
            "profile_image_url": "./assets/images/characters/7_Daichi_Sawamura_Practice.png",
            "personal_page_url": null
        },
        "8": {
            "id": 8,
            "school": "Karasuno",
            "name": "Koshi Sugawara",
            "name_jp": "菅原孝支",
            "variant": "Afterschool",
            "rarity": "SP",
            "position": "S",
            "profile_image_url": "./assets/images/characters/8_Koshi_Sugawara_Afterschool.png",
            "personal_page_url": "https://naoshisan.com/?p=3449"
        },
        "9": {
            "id": 9,
            "school": "Karasuno",
            "name": "Koshi Sugawara",
            "name_jp": "菅原孝支",
            "variant": null,
            "rarity": "SR",
            "position": "S",
            "profile_image_url": "./assets/images/characters/9_Koshi_Sugawara.png",
            "personal_page_url": null
        },
        "10": {
            "id": 10,
            "school": "Karasuno",
            "name": "Asahi Azumane",
            "name_jp": "東峰旭",
            "variant": null,
            "rarity": "SSR",
            "position": "WS",
            "profile_image_url": "./assets/images/characters/10_Asahi_Azumane.png",
            "personal_page_url": null
        },
        "11": {
            "id": 11,
            "school": "Karasuno",
            "name": "Asahi Azumane",
            "name_jp": "東峰旭",
            "variant": "Practice",
            "rarity": "SR",
            "position": "WS",
            "profile_image_url": "./assets/images/characters/11_Asahi_Azumane_Practice.png",
            "personal_page_url": null
        },
        "12": {
            "id": 12,
            "school": "Karasuno",
            "name": "Yuu Nishinoya",
            "name_jp": "西谷夕",
            "variant": "Afterschool",
            "rarity": "SP",
            "position": "L",
            "profile_image_url": "./assets/images/characters/12_Yuu_Nishinoya_Afterschool.png",
            "personal_page_url": "https://naoshisan.com/?p=3417"
        },
        "13": {
            "id": 13,
            "school": "Karasuno",
            "name": "Yuu Nishinoya",
            "name_jp": "西谷夕",
            "variant": null,
            "rarity": "SSR",
            "position": "L",
            "profile_image_url": "./assets/images/characters/13_Yuu_Nishinoya.png",
            "personal_page_url": "https://naoshisan.com/?p=3462"
        },
        "14": {
            "id": 14,
            "school": "Karasuno",
            "name": "Yuu Nishinoya",
            "name_jp": "西谷夕",
            "variant": "Practice",
            "rarity": "SR",
            "position": "L",
            "profile_image_url": "./assets/images/characters/14_Yuu_Nishinoya_Practice.png",
            "personal_page_url": null
        },
        "15": {
            "id": 15,
            "school": "Karasuno",
            "name": "Ryunosuke Tanaka",
            "name_jp": "田中龍之介",
            "variant": null,
            "rarity": "SSR",
            "position": "WS",
            "profile_image_url": "./assets/images/characters/15_Ryunosuke_Tanaka.png",
            "personal_page_url": null
        },
        "16": {
            "id": 16,
            "school": "Karasuno",
            "name": "Ryunosuke Tanaka",
            "name_jp": "田中龍之介",
            "variant": "Practice",
            "rarity": "SR",
            "position": "WS",
            "profile_image_url": "./assets/images/characters/16_Ryunosuke_Tanaka_Practice.png",
            "personal_page_url": null
        },
        "17": {
            "id": 17,
            "school": "Karasuno",
            "name": "Kei Tsukishima",
            "name_jp": "月島蛍",
            "variant": "Fireworks",
            "rarity": "SP",
            "position": "MB",
            "profile_image_url": "./assets/images/characters/17_Kei_Tsukishima_Fireworks.png",
            "personal_page_url": null
        },
        "18": {
            "id": 18,
            "school": "Karasuno",
            "name": "Kei Tsukishima",
            "name_jp": "月島蛍",
            "variant": null,
            "rarity": "SSR",
            "position": "MB",
            "profile_image_url": "./assets/images/characters/18_Kei_Tsukishima.png",
            "personal_page_url": null
        },
        "19": {
            "id": 19,
            "school": "Karasuno",
            "name": "Kei Tsukishima",
            "name_jp": "月島蛍",
            "variant": "Practice",
            "rarity": "SR",
            "position": "MB",
            "profile_image_url": "./assets/images/characters/19_Kei_Tsukishima_Practice.png",
            "personal_page_url": null
        },
        "20": {
            "id": 20,
            "school": "Karasuno",
            "name": "Tadashi Yamaguchi",
            "name_jp": "山口忠",
            "variant": null,
            "rarity": "SR",
            "position": "MB",
            "profile_image_url": "./assets/images/characters/20_Tadashi_Yamaguchi.png",
            "personal_page_url": null
        },
        "21": {
            "id": 21,
            "school": "Karasuno",
            "name": "Tadashi Yamaguchi",
            "name_jp": "山口忠",
            "variant": "Practice",
            "rarity": "R",
            "position": "MB",
            "profile_image_url": "./assets/images/characters/21_Tadashi_Yamaguchi_Practice.png",
            "personal_page_url": null
        },
        "22": {
            "id": 22,
            "school": "Karasuno",
            "name": "Chikara Ennoshita",
            "name_jp": "縁下力",
            "variant": null,
            "rarity": "SR",
            "position": "WS",
            "profile_image_url": "./assets/images/characters/22_Chikara_Ennoshita.png",
            "personal_page_url": null
        },
        "23": {
            "id": 23,
            "school": "Karasuno",
            "name": "Chikara Ennoshita",
            "name_jp": "縁下力",
            "variant": "Practice",
            "rarity": "R",
            "position": "WS",
            "profile_image_url": "./assets/images/characters/23_Chikara_Ennoshita_Practice.png",
            "personal_page_url": null
        },
        "24": {
            "id": 24,
            "school": "Karasuno",
            "name": "Hisashi Kinoshita",
            "name_jp": "木下久志",
            "variant": null,
            "rarity": "R",
            "position": "WS",
            "profile_image_url": "./assets/images/characters/24_Hisashi_Kinoshita.png",
            "personal_page_url": null
        },
        "25": {
            "id": 25,
            "school": "Karasuno",
            "name": "Kazuhito Narita",
            "name_jp": "成田一仁",
            "variant": null,
            "rarity": "R",
            "position": "MB",
            "profile_image_url": "./assets/images/characters/25_Kazuhito_Narita.png",
            "personal_page_url": null
        },
        "26": {
            "id": 26,
            "school": "Aoba Johsai",
            "name": "Toru Oikawa",
            "name_jp": "及川徹",
            "variant": null,
            "rarity": "UR",
            "position": "S",
            "profile_image_url": "./assets/images/characters/26_Toru_Oikawa.png",
            "personal_page_url": "https://naoshisan.com/?p=3511"
        },
        "27": {
            "id": 27,
            "school": "Aoba Johsai",
            "name": "Toru Oikawa",
            "name_jp": "及川徹",
            "variant": "Practice",
            "rarity": "SSR",
            "position": "S",
            "profile_image_url": "./assets/images/characters/27_Toru_Oikawa_Practice.png",
            "personal_page_url": null
        },
        "28": {
            "id": 28,
            "school": "Aoba Johsai",
            "name": "Hajime Iwaizumi",
            "name_jp": "岩泉一",
            "variant": null,
            "rarity": "SSR",
            "position": "WS",
            "profile_image_url": "./assets/images/characters/28_Hajime_Iwaizumi.png",
            "personal_page_url": null
        },
        "29": {
            "id": 29,
            "school": "Aoba Johsai",
            "name": "Hajime Iwaizumi",
            "name_jp": "岩泉一",
            "variant": null,
            "rarity": "SR",
            "position": "WS",
            "profile_image_url": "./assets/images/characters/29_Hajime_Iwaizumi.png",
            "personal_page_url": null
        },
        "30": {
            "id": 30,
            "school": "Aoba Johsai",
            "name": "Issei Matsukawa",
            "name_jp": "松川一静",
            "variant": null,
            "rarity": "SR",
            "position": "MB",
            "profile_image_url": "./assets/images/characters/30_Issei_Matsukawa.png",
            "personal_page_url": null
        },
        "31": {
            "id": 31,
            "school": "Aoba Johsai",
            "name": "Takahiro Hanamaki",
            "name_jp": "花巻貴大",
            "variant": null,
            "rarity": "SR",
            "position": "WS",
            "profile_image_url": "./assets/images/characters/31_Takahiro_Hanamaki.png",
            "personal_page_url": null
        },
        "32": {
            "id": 32,
            "school": "Aoba Johsai",
            "name": "Shigeru Yahaba",
            "name_jp": "矢巾秀",
            "variant": null,
            "rarity": "SR",
            "position": "S",
            "profile_image_url": "./assets/images/characters/32_Shigeru_Yahaba.png",
            "personal_page_url": null
        },
        "33": {
            "id": 33,
            "school": "Aoba Johsai",
            "name": "Shinji Watari",
            "name_jp": "渡親治",
            "variant": null,
            "rarity": "SR",
            "position": "L",
            "profile_image_url": "./assets/images/characters/33_Shinji_Watari.png",
            "personal_page_url": null
        },
        "34": {
            "id": 34,
            "school": "Aoba Johsai",
            "name": "Yutaro Kindaichi",
            "name_jp": "金田一勇太郎",
            "variant": null,
            "rarity": "SR",
            "position": "MB",
            "profile_image_url": "./assets/images/characters/34_Yutaro_Kindaichi.png",
            "personal_page_url": null
        },
        "35": {
            "id": 35,
            "school": "Aoba Johsai",
            "name": "Akira Kunimi",
            "name_jp": "国見英",
            "variant": null,
            "rarity": "SR",
            "position": "OP",
            "profile_image_url": "./assets/images/characters/35_Akira_Kunimi.png",
            "personal_page_url": null
        },
        "36": {
            "id": 36,
            "school": "Aoba Johsai",
            "name": "Kentaro Kyotani",
            "name_jp": "京谷賢太郎",
            "variant": null,
            "rarity": "SSR",
            "position": "OP",
            "profile_image_url": "./assets/images/characters/36_Kentaro_Kyotani.png",
            "personal_page_url": null
        },
        "37": {
            "id": 37,
            "school": "Aoba Johsai",
            "name": "Kentaro Kyotani",
            "name_jp": "京谷賢太郎",
            "variant": null,
            "rarity": "SR",
            "position": "OP",
            "profile_image_url": "./assets/images/characters/37_Kentaro_Kyotani.png",
            "personal_page_url": null
        },
        "38": {
            "id": 38,
            "school": "Date Tech",
            "name": "Takanobu Aone",
            "name_jp": "青根高伸",
            "variant": "Beach",
            "rarity": "SP",
            "position": "MB",
            "profile_image_url": "./assets/images/characters/38_Takanobu_Aone_Beach.png",
            "personal_page_url": null
        },
        "39": {
            "id": 39,
            "school": "Date Tech",
            "name": "Takanobu Aone",
            "name_jp": "青根高伸",
            "variant": null,
            "rarity": "SSR",
            "position": "MB",
            "profile_image_url": "./assets/images/characters/39_Takanobu_Aone.png",
            "personal_page_url": null
        },
        "40": {
            "id": 40,
            "school": "Date Tech",
            "name": "Takanobu Aone",
            "name_jp": "青根高伸",
            "variant": "Practice",
            "rarity": "SR",
            "position": "MB",
            "profile_image_url": "./assets/images/characters/40_Takanobu_Aone_Practice.png",
            "personal_page_url": null
        },
        "41": {
            "id": 41,
            "school": "Date Tech",
            "name": "Kenji Futakuchi",
            "name_jp": "二口堅治",
            "variant": null,
            "rarity": "SSR",
            "position": "WS",
            "profile_image_url": "./assets/images/characters/41_Kenji_Futakuchi.png",
            "personal_page_url": null
        },
        "42": {
            "id": 42,
            "school": "Date Tech",
            "name": "Kenji Futakuchi",
            "name_jp": "二口堅治",
            "variant": "Practice",
            "rarity": "SR",
            "position": "WS",
            "profile_image_url": "./assets/images/characters/42_Kenji_Futakuchi_Practice.png",
            "personal_page_url": null
        },
        "43": {
            "id": 43,
            "school": "Date Tech",
            "name": "Kanji Koganegawa",
            "name_jp": "黄金川貫至",
            "variant": null,
            "rarity": "SSR",
            "position": "S",
            "profile_image_url": "./assets/images/characters/43_Takanobu_Obara.png",
            "personal_page_url": null
        },
        "44": {
            "id": 44,
            "school": "Date Tech",
            "name": "Kanji Koganegawa",
            "name_jp": "黄金川貫至",
            "variant": "Practice",
            "rarity": "SR",
            "position": "S",
            "profile_image_url": "./assets/images/characters/44_Takanobu_Obara_Practice.png",
            "personal_page_url": null
        },
        "45": {
            "id": 45,
            "school": "Date Tech",
            "name": "Kosuke Sakunami",
            "name_jp": "作並浩輔",
            "variant": null,
            "rarity": "R",
            "position": "L",
            "profile_image_url": "./assets/images/characters/45_Kosuke_Sakunami.png",
            "personal_page_url": null
        },
        "46": {
            "id": 46,
            "school": "Date Tech",
            "name": "Yasushi Kamasaki",
            "name_jp": "鎌崎靖志",
            "variant": null,
            "rarity": "SR",
            "position": "MB",
            "profile_image_url": "./assets/images/characters/46_Yasushi_Kamasaki.png",
            "personal_page_url": null
        },
        "47": {
            "id": 47,
            "school": "Date Tech",
            "name": "Kaname Moniwa",
            "name_jp": "茂庭要",
            "variant": null,
            "rarity": "SR",
            "position": "S",
            "profile_image_url": "./assets/images/characters/47_Kaname_Moniwa.png",
            "personal_page_url": null
        },
        "48": {
            "id": 48,
            "school": "Date Tech",
            "name": "Takehito Sasaya",
            "name_jp": "笹谷武仁",
            "variant": null,
            "rarity": "SSR",
            "position": "OP",
            "profile_image_url": "./assets/images/characters/48_Takehito_Sasaya.png",
            "personal_page_url": null
        },
        "49": {
            "id": 49,
            "school": "Date Tech",
            "name": "Takehito Sasaya",
            "name_jp": "笹谷武仁",
            "variant": "Practice",
            "rarity": "SR",
            "position": "OP",
            "profile_image_url": "./assets/images/characters/49_Takehito_Sasaya_Practice.png",
            "personal_page_url": null
        },
        "50": {
            "id": 50,
            "school": "Date Tech",
            "name": "Yutaka Obara",
            "name_jp": "小原豊",
            "variant": null,
            "rarity": "SR",
            "position": "WS",
            "profile_image_url": "./assets/images/characters/50_Yutaka_Obara.png",
            "personal_page_url": null
        },
        "51": {
            "id": 51,
            "school": "Date Tech",
            "name": "Taro Onagawa",
            "name_jp": "女川太郎",
            "variant": null,
            "rarity": "R",
            "position": "OP",
            "profile_image_url": "./assets/images/characters/51_Taro_Onagawa.png",
            "personal_page_url": null
        },
        "52": {
            "id": 52,
            "school": "Date Tech",
            "name": "Jingo Fukiage",
            "name_jp": "吹上仁悟",
            "variant": null,
            "rarity": "R",
            "position": "MB",
            "profile_image_url": "./assets/images/characters/52_Jingo_Fukiage.png",
            "personal_page_url": null
        },
        "53": {
            "id": 53,
            "school": "Shiratorizawa",
            "name": "Wakatoshi Ushijima",
            "name_jp": "牛島若利",
            "variant": null,
            "rarity": "UR",
            "position": "OP",
            "profile_image_url": "./assets/images/characters/53_Wakatoshi_Ushijima.png",
            "personal_page_url": "https://naoshisan.com/?p=3516"
        },
        "54": {
            "id": 54,
            "school": "Shiratorizawa",
            "name": "Satori Tendo",
            "name_jp": "天童覚",
            "variant": null,
            "rarity": "SSR",
            "position": "MB",
            "profile_image_url": "./assets/images/characters/54_Satori_Tendo.png",
            "personal_page_url": null
        },
        "55": {
            "id": 55,
            "school": "Shiratorizawa",
            "name": "Tsutomu Goshiki",
            "name_jp": "五色工",
            "variant": null,
            "rarity": "SSR",
            "position": "WS",
            "profile_image_url": "./assets/images/characters/55_Tsutomu_Goshiki.png",
            "personal_page_url": null
        },
        "56": {
            "id": 56,
            "school": "Shiratorizawa",
            "name": "Kenjiro Shirabu",
            "name_jp": "白布賢二郎",
            "variant": null,
            "rarity": "SSR",
            "position": "S",
            "profile_image_url": "./assets/images/characters/56_Kenjiro_Shirabu.png",
            "personal_page_url": null
        },
        "57": {
            "id": 57,
            "school": "Shiratorizawa",
            "name": "Eita Semi",
            "name_jp": "瀬見英太",
            "variant": null,
            "rarity": "SSR",
            "position": "S",
            "profile_image_url": "./assets/images/characters/57_Eita_Semi.png",
            "personal_page_url": null
        },
        "58": {
            "id": 58,
            "school": "Shiratorizawa",
            "name": "Reon Ohira",
            "name_jp": "大平獅音",
            "variant": null,
            "rarity": "SSR",
            "position": "WS",
            "profile_image_url": "./assets/images/characters/58_Reon_Ohira.png",
            "personal_page_url": null
        },
        "59": {
            "id": 59,
            "school": "Shiratorizawa",
            "name": "Taichi Kawanishi",
            "name_jp": "川西太一",
            "variant": null,
            "rarity": "SR",
            "position": "MB",
            "profile_image_url": "./assets/images/characters/59_Taichi_Kawanishi.png",
            "personal_page_url": null
        },
        "60": {
            "id": 60,
            "school": "Shiratorizawa",
            "name": "Hayato Yamagata",
            "name_jp": "山形隼人",
            "variant": null,
            "rarity": "SSR",
            "position": "L",
            "profile_image_url": "./assets/images/characters/60_Hayato_Yamagata.png",
            "personal_page_url": null
        },
        "61": {
            "id": 61,
            "school": "Fukurodani",
            "name": "Kotaro Bokuto",
            "name_jp": "木兎光太郎",
            "variant": "Beach",
            "rarity": "SP",
            "position": "WS",
            "profile_image_url": "./assets/images/characters/61_Kotaro_Bokuto_Beach.png",
            "personal_page_url": "https://naoshisan.com/?p=3437"
        },
        "62": {
            "id": 62,
            "school": "Fukurodani",
            "name": "Kotaro Bokuto",
            "name_jp": "木兎光太郎",
            "variant": null,
            "rarity": "UR",
            "position": "WS",
            "profile_image_url": "./assets/images/characters/62_Kotaro_Bokuto.png",
            "personal_page_url": "https://naoshisan.com/?p=3437"
        },
        "63": {
            "id": 63,
            "school": "Fukurodani",
            "name": "Keiji Akaashi",
            "name_jp": "赤葦京治",
            "variant": "Beach",
            "rarity": "SP",
            "position": "S",
            "profile_image_url": "./assets/images/characters/63_Keiji_Akaashi_Beach.png",
            "personal_page_url": null
        },
        "64": {
            "id": 64,
            "school": "Fukurodani",
            "name": "Keiji Akaashi",
            "name_jp": "赤葦京治",
            "variant": null,
            "rarity": "SSR",
            "position": "S",
            "profile_image_url": "./assets/images/characters/64_Keiji_Akaashi.png",
            "personal_page_url": null
        },
        "65": {
            "id": 65,
            "school": "Fukurodani",
            "name": "Akinori Konoha",
            "name_jp": "木葉秋紀",
            "variant": null,
            "rarity": "SSR",
            "position": "OP",
            "profile_image_url": "./assets/images/characters/65_Akinori_Konoha.png",
            "personal_page_url": null
        },
        "66": {
            "id": 66,
            "school": "Fukurodani",
            "name": "Yamato Sarukui",
            "name_jp": "猿杙大和",
            "variant": null,
            "rarity": "SR",
            "position": "WS",
            "profile_image_url": "./assets/images/characters/66_Yamato_Sarukui.png",
            "personal_page_url": null
        },
        "67": {
            "id": 67,
            "school": "Fukurodani",
            "name": "Haruki Komi",
            "name_jp": "小見春樹",
            "variant": null,
            "rarity": "SSR",
            "position": "L",
            "profile_image_url": "./assets/images/characters/67_Haruki_Komi.png",
            "personal_page_url": null
        },
        "68": {
            "id": 68,
            "school": "Fukurodani",
            "name": "Wataru Onaga",
            "name_jp": "尾長渉",
            "variant": null,
            "rarity": "R",
            "position": "MB",
            "profile_image_url": "./assets/images/characters/68_Wataru_Onaga.png",
            "personal_page_url": null
        },
        "69": {
            "id": 69,
            "school": "Fukurodani",
            "name": "Tatsuo Washio",
            "name_jp": "鷲尾辰生",
            "variant": null,
            "rarity": "SSR",
            "position": "MB",
            "profile_image_url": "./assets/images/characters/69_Tatsuo_Washio.png",
            "personal_page_url": null
        },
        "70": {
            "id": 70,
            "school": "Jozenji",
            "name": "Yuji Terushima",
            "name_jp": "照島遊児",
            "variant": null,
            "rarity": "SSR",
            "position": "WS",
            "profile_image_url": "./assets/images/characters/70_Yuji_Terushima.png",
            "personal_page_url": null
        },
        "71": {
            "id": 71,
            "school": "Jozenji",
            "name": "Kazuma Bobata",
            "name_jp": "母畑和馬",
            "variant": null,
            "rarity": "R",
            "position": "MB",
            "profile_image_url": "./assets/images/characters/71_Kazuma_Bobata.png",
            "personal_page_url": null
        },
        "72": {
            "id": 72,
            "school": "Jozenji",
            "name": "Takeharu Futamata",
            "name_jp": "二岐丈春",
            "variant": null,
            "rarity": "SR",
            "position": "S",
            "profile_image_url": "./assets/images/characters/72_Takeharu_Futamata.png",
            "personal_page_url": null
        },
        "73": {
            "id": 73,
            "school": "Jozenji",
            "name": "Katsumichi Higashiyama",
            "name_jp": "東山勝道",
            "variant": null,
            "rarity": "SR",
            "position": "WS",
            "profile_image_url": "./assets/images/characters/73_Katsumichi_Higashiyama.png",
            "personal_page_url": null
        },
        "74": {
            "id": 74,
            "school": "Jozenji",
            "name": "Nobuyoshi Īzaka",
            "name_jp": "飯坂信義",
            "variant": null,
            "rarity": "R",
            "position": "MB",
            "profile_image_url": "./assets/images/characters/74_Nobuyoshi__zaka.png",
            "personal_page_url": null
        },
        "75": {
            "id": 75,
            "school": "Jozenji",
            "name": "Rintarō Numajiri",
            "name_jp": "沼尻凛太郎",
            "variant": null,
            "rarity": "R",
            "position": "OP",
            "profile_image_url": "./assets/images/characters/75_Rintar__Numajiri.png",
            "personal_page_url": null
        },
        "76": {
            "id": 76,
            "school": "Jozenji",
            "name": "Arata Tsuchiyu",
            "name_jp": "土湯新",
            "variant": null,
            "rarity": "R",
            "position": "L",
            "profile_image_url": "./assets/images/characters/76_Arata_Tsuchiyu.png",
            "personal_page_url": null
        },
        "77": {
            "id": 77,
            "school": "Inarizaki",
            "name": "Atsumu Miya",
            "name_jp": "宮侑",
            "variant": null,
            "rarity": "UR",
            "position": "S",
            "profile_image_url": "./assets/images/characters/77_Atsumu_Miya.png",
            "personal_page_url": "https://naoshisan.com/?p=3521"
        },
        "78": {
            "id": 78,
            "school": "Inarizaki",
            "name": "Osamu Miya",
            "name_jp": "宮治",
            "variant": null,
            "rarity": "UR",
            "position": "OP",
            "profile_image_url": "./assets/images/characters/78_Osamu_Miya.png",
            "personal_page_url": null
        },
        "79": {
            "id": 79,
            "school": "Inarizaki",
            "name": "Shinsuke Kita",
            "name_jp": "北信介",
            "variant": null,
            "rarity": "SSR",
            "position": "WS",
            "profile_image_url": "./assets/images/characters/79_Shinsuke_Kita.png",
            "personal_page_url": null
        },
        "80": {
            "id": 80,
            "school": "Inarizaki",
            "name": "Rintaro Suna",
            "name_jp": "角名倫太郎",
            "variant": null,
            "rarity": "SSR",
            "position": "MB",
            "profile_image_url": "./assets/images/characters/80_Rintaro_Suna.png",
            "personal_page_url": null
        },
        "81": {
            "id": 81,
            "school": "Inarizaki",
            "name": "Aran Ojiro",
            "name_jp": "尾白アラン",
            "variant": null,
            "rarity": "SSR",
            "position": "WS",
            "profile_image_url": "./assets/images/characters/81_Aran_Ojiro.png",
            "personal_page_url": null
        },
        "82": {
            "id": 82,
            "school": "Inarizaki",
            "name": "Michiaki Akagi",
            "name_jp": "赤木路成",
            "variant": null,
            "rarity": "SSR",
            "position": "L",
            "profile_image_url": "./assets/images/characters/82_Michiaki_Akagi.png",
            "personal_page_url": null
        },
        "83": {
            "id": 83,
            "school": "Inarizaki",
            "name": "Yui Ginshima",
            "name_jp": "銀島結",
            "variant": null,
            "rarity": "SSR",
            "position": "WS",
            "profile_image_url": "./assets/images/characters/83_Yui_Ginshima.png",
            "personal_page_url": null
        },
        "84": {
            "id": 84,
            "school": "Inarizaki",
            "name": "Atsumu Oomimi",
            "name_jp": "大耳練",
            "variant": null,
            "rarity": "SR",
            "position": "MB",
            "profile_image_url": "./assets/images/characters/84_Atsumu_Oomimi.png",
            "personal_page_url": null
        },
        "85": {
            "id": 85,
            "school": "Inarizaki",
            "name": "Yuto Osaku",
            "name_jp": "小作裕渡",
            "variant": null,
            "rarity": "R",
            "position": "WS",
            "profile_image_url": "./assets/images/characters/85_Yuto_Osaku.png",
            "personal_page_url": null
        },
        "86": {
            "id": 86,
            "school": "Inarizaki",
            "name": "Heisuke Riseiki",
            "name_jp": "理石平介",
            "variant": null,
            "rarity": "R",
            "position": "WS",
            "profile_image_url": "./assets/images/characters/86_Heisuke_Riseiki.png",
            "personal_page_url": null
        },
        "87": {
            "id": 87,
            "school": "Kamomedai",
            "name": "Korai Hoshiumi",
            "name_jp": "星海光来",
            "variant": null,
            "rarity": "UR",
            "position": "WS",
            "profile_image_url": "./assets/images/characters/87_Korai_Hoshiumi.png",
            "personal_page_url": "https://naoshisan.com/?p=3533"
        },
        "88": {
            "id": 88,
            "school": "Kamomedai",
            "name": "Sachiro Hirugami",
            "name_jp": "昼神幸郎",
            "variant": null,
            "rarity": "UR",
            "position": "MB",
            "profile_image_url": "./assets/images/characters/88_Sachiro_Hirugami.png",
            "personal_page_url": "https://naoshisan.com/?p=3538"
        },
        "89": {
            "id": 89,
            "school": "Nekoma",
            "name": "Kenma Kozume",
            "name_jp": "孤爪研磨",
            "variant": "Hanami",
            "rarity": "SP",
            "position": "S",
            "profile_image_url": "./assets/images/characters/89_Kenma_Kozume_Hanami.png",
            "personal_page_url": null
        },
        "90": {
            "id": 90,
            "school": "Nekoma",
            "name": "Kenma Kozume",
            "name_jp": "孤爪研磨",
            "variant": null,
            "rarity": "SSR",
            "position": "S",
            "profile_image_url": "./assets/images/characters/90_Kenma_Kozume.png",
            "personal_page_url": null
        },
        "91": {
            "id": 91,
            "school": "Nekoma",
            "name": "Tetsuro Kuroo",
            "name_jp": "黒尾鉄朗",
            "variant": null,
            "rarity": "UR",
            "position": "MB",
            "profile_image_url": "./assets/images/characters/91_Tetsuro_Kuroo.png",
            "personal_page_url": "https://naoshisan.com/?p=3427"
        },
        "92": {
            "id": 92,
            "school": "Nekoma",
            "name": "Tetsuro Kuroo",
            "name_jp": "黒尾鉄朗",
            "variant": null,
            "rarity": "SSR",
            "position": "MB",
            "profile_image_url": "./assets/images/characters/92_Tetsuro_Kuroo.png",
            "personal_page_url": "https://naoshisan.com/?p=3554"
        },
        "93": {
            "id": 93,
            "school": "Nekoma",
            "name": "Morisuke Yaku",
            "name_jp": "夜久衛輔",
            "variant": null,
            "rarity": "SSR",
            "position": "L",
            "profile_image_url": "./assets/images/characters/93_Morisuke_Yaku.png",
            "personal_page_url": null
        },
        "94": {
            "id": 94,
            "school": "Nekoma",
            "name": "Lev Haiba",
            "name_jp": "灰羽リエーフ",
            "variant": null,
            "rarity": "SSR",
            "position": "MB",
            "profile_image_url": "./assets/images/characters/94_Lev_Haiba.png",
            "personal_page_url": null
        },
        "95": {
            "id": 95,
            "school": "Nekoma",
            "name": "Taketora Yamamoto",
            "name_jp": "山本猛虎",
            "variant": null,
            "rarity": "SR",
            "position": "WS",
            "profile_image_url": "./assets/images/characters/95_Takeru_Yamamoto.png",
            "personal_page_url": null
        },
        "96": {
            "id": 96,
            "school": "Nekoma",
            "name": "Nobuyuki Kai",
            "name_jp": "海信行",
            "variant": null,
            "rarity": "SR",
            "position": "OP",
            "profile_image_url": "./assets/images/characters/96_Nobuyuki_Kai.png",
            "personal_page_url": null
        },
        "97": {
            "id": 97,
            "school": "Nekoma",
            "name": "Shohei Fukunaga",
            "name_jp": "福永招平",
            "variant": null,
            "rarity": "SR",
            "position": "WS",
            "profile_image_url": "./assets/images/characters/97_Shohei_Fukunaga.png",
            "personal_page_url": null
        },
        "98": {
            "id": 98,
            "school": "Nekoma",
            "name": "Soh Inuoka",
            "name_jp": "犬岡走",
            "variant": null,
            "rarity": "SR",
            "position": "MB",
            "profile_image_url": "./assets/images/characters/98_Soh_Inuoka.png",
            "personal_page_url": null
        },
        "99": {
            "id": 99,
            "school": "Nekoma",
            "name": "Yuki Shibayama",
            "name_jp": "芝山優生",
            "variant": null,
            "rarity": "R",
            "position": "L",
            "profile_image_url": "./assets/images/characters/99_Yuki_Shibayama.png",
            "personal_page_url": null
        },
        "100": {
            "id": 100,
            "school": "Nekoma",
            "name": "Tamahiko Teshiro",
            "name_jp": "手白球彦",
            "variant": null,
            "rarity": "SR",
            "position": "S",
            "profile_image_url": "./assets/images/characters/100_Tamahiko_Teshiro.png",
            "personal_page_url": null
        },
        "101": {
            "id": 101,
            "school": "Seidatsuzan",
            "name": "Kiyoomi Sakusa",
            "name_jp": "佐久早聖臣",
            "variant": null,
            "rarity": "UR",
            "position": "WS",
            "profile_image_url": "./assets/images/characters/101_Kiyoomi_Sakusa.png",
            "personal_page_url": null
        },
        "102": {
            "id": 102,
            "school": "Seidatsuzan",
            "name": "Motoya Komori",
            "name_jp": "古森元也",
            "variant": null,
            "rarity": "UR",
            "position": "L",
            "profile_image_url": "./assets/images/characters/102_Motoya_Komori.png",
            "personal_page_url": null
        },
        "103": {
            "id": 103,
            "school": "Nekoma",
            "name": "Kenma Kozume",
            "name_jp": "孤爪研磨",
            "variant": null,
            "rarity": "SR",
            "position": "S",
            "profile_image_url": "./assets/images/characters/103_Kenma.png",
            "personal_page_url": null
        },
        "104": {
            "id": 104,
            "school": "Nekoma",
            "name": "Tetsuro Kuroo",
            "name_jp": "黒尾鉄朗",
            "variant": null,
            "rarity": "SP",
            "position": "MB",
            "profile_image_url": "./assets/images/characters/104_Tetsuro_Kuroo.png",
            "personal_page_url": "https://naoshisan.com/?p=4963"
        },
    }
};